import { createContext } from "react";

export const MainContext = createContext({
    drawer: '',
    setDrawer: () => { },
    signUpDialog: '',
    setSignUpDialog: () => { },
    loginDialog: '',
    setLoginDialog: () => { },
    tabIndex: '',
    setTabIndex: () => { },
    handleTabChange: () => { },
    submitSignUp: () => { },
    setSnackbar: () => { },
    submitLogin: () => { },
    submitLogout: () => { },
    isLogin: "",
    setIsLogin: () => { },
    setRememberMe: () => { },
    getLoan: () => { },
    cookies: "",
    balance: '',
    getAmount: () => { },
    getAllTransActions: () => { },
    allTransActions: "",
    numberFormatter: () => { },
    getTurnover: () => { },
    turnover: () => { },
    sendMoney: () => { },
    accInfo : '',
    navigateHome: () => {},
})